apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-player
  labels:
    app: app-player
    release: my-release
spec:
  selector:
    matchLabels:
      app: app-player
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 10s
