# config file version
apiVersion: 1

datasources:
- name: 'Elasticsearch'
  type: 'elasticsearch'
  access: 'proxy'
  database: '[jaeger-span-]YYYY-MM-DD'
  url: 'http://elasticsearch:9200'
  editable: true
  jsonData:
    interval: 'Daily'
    timeField: 'startTimeMillis'
    esVersion: 70
    timeInterval: '10s'
    logMessageField: 'message'
    logLevelField: 'fields.level'
  

