{
 "title": "Container Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container_name", "label": "container_name" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "node_id", "label": "Swarm Node", "query": "node_meta" }
  ]
 },
 "panels": [
  {
   "title": "Menu",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "\nVoltar para a página principal\n\nhttp://jaeger:3000/d/fxKiDoRMz/all-containers-semaphore?orgId=1\n\n\n"
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU usage by Containers $container_name",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"$container_name.*\", instance!~\"^cadvisor.*\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory usage by Containers $container_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"$container_name.*\", instance!~\"^cadvisor.*\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network received by Containers $container_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_task_name=~\"$container_name.*\", instance!~\"^cadvisor.*\"}[$interval])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network transmitted by Containers $container_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_task_name=~\"$container_name.*\", instance!~\"^cadvisor.*\"}[$interval])) by (container_label_com_docker_swarm_task_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}