{
 "title": "Health Dashborad",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Docker CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 } },
  {
   "title": "CPU All Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id,name))",
     "legendFormat": "All Containers"
    }
   ]
  },
  {
   "title": "CPU By Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory All Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{image!=\"\"})",
     "legendFormat": "All Containers"
    }
   ]
  },
  {
   "title": "Memory By Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}