{
 "title": "Node Exporter for Prometheus Dashboard",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "CPU",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "Rede",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$node\"}, nodename)"
   }
  ]
 },
 "panels": [
  { "title": "Visão geral dos recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Visão geral de recursos do servidor (10 linhas por página)",
   "type": "table-old",
   "description": "\n",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[5m])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "Max Read"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "Max Write"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
     "legendFormat": "largura de banda"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
     "legendFormat": "largura de banda"
    }
   ]
  },
  {
   "title": " $job: Total geral e uso médio geral da CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Carga total" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\", mode='system'})",
     "legendFormat": "Número total de núcleos"
    },
    {
     "expr": "sum(node_load5{job=\"$job\"})",
     "legendFormat": "5 minutos de carga total"
    },
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "5 minutos de carga total"
    }
   ]
  },
  {
   "title": "$job: Memoria",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"})",
     "legendFormat": "Uso total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"})",
     "legendFormat": "Usado"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{job=~\"$job\"}))*100",
     "legendFormat": "Uso médio"
    }
   ]
  },
  {
   "title": "$job: Disco total e médio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": " Disco total" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Disco total"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Uso total"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "Uso médio total"
    }
   ]
  },
  { "title": "Detalhes：$show_hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Tempo",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Uso total da CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Uso de memória"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Uso Partição ({{mountpoint}})"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "Uso Swap"
    }
   ]
  },
  {
   "title": "$show_hostname：Disponível em cada partição",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Fluxo: $device",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": " Upload (-) / Download (+)" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_inDownload"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_outUpload"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": " Número de nós restantes: $maxmount ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Memória ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Arquivos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 18 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
     "legendFormat": "Uso do sistema"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
     "legendFormat": "Uso do usuário"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
     "legendFormat": "Uso de E/S de disco"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
     "legendFormat": "Uso total"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Memória total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Usava"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Acessível"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Taxa de uso"
    }
   ]
  },
  {
   "title": "Rede $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "Download（-）/Upload（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}_inUpload"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}_outDownload"
    }
   ]
  },
  {
   "title": " Carga média do sistema",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "Último minuto"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "Últimos 5 minutos"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "Últimos 15 minutos"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "Núcleos"
    }
   ]
  },
  {
   "title": "Disco E/S",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "Bps", "label": "Leitura (-) / gravação (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Leitura"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Escrita"
    }
   ]
  },
  {
   "title": "Uso de disco",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Taxa de leitura e gravação de disco（IOPS）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    {
     "format": "iops",
     "label": "Leitura (-) / gravação (+) operações de E/S"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Leitura"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Escrita"
    }
   ]
  },
  {
   "title": "Tempo em operações de E/S por segundo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_%_E/S"
    }
   ]
  },
  {
   "title": "Arquivos abertos / Alternâncias de contexto",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Arquivos usados" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "Arquivos usados"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m])",
     "legendFormat": "Alternâncias de contexto"
    }
   ]
  },
  {
   "title": "Soquete de rede",
   "type": "graph",
   "description": "Total de todos os soquetes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  }
 ]
}