server:
  port: 9005

spring:
  application:
    name: Service A

opentracing:
  jaeger:
    enable: true
    http-sender:
      url: http://192.168.15.150:14268/api/traces
  
    enable-b3-propagation: true
    log-spans: false
  
service:
  outgoing:
    url: ""
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    httptrace:
      enabled: true